version: '3.8'

services:
  docker:
    image: docker:dind
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - ./docker-certs:/certs/client
      - ./data:/var/jenkins_home
    networks: 
      - jenkins
    ports:
      - 2376:2376
  app:
    build:
      context: .
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    volumes:
      - ./docker-certs:/certs/client:ro
      - ./data:/var/jenkins_home
    networks: 
      - jenkins
    ports:
      - 8080:8080
      - 50000:50000

networks:
  jenkins:
    name: jenkins
    driver: bridge
